---
title: "Data_Wrangling_i"
output: html_document
---

```{r}
library(tidyverse)
```


## LImport Datasets
```{r}
#never use read.csv, always use read_csv; .csv allows you to call variables not using full name

litters_data <- read_csv(file = "./data_import_examples/FAS_litters.csv")
litters_data <- janitor::clean_names(litters_data)
pups_data <- read_csv(file = "./data_import_examples/FAS_pups.csv")
pups_data <- janitor::clean_names(pups_data)
```


## Select
```{r}
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight)

select(litters_data, group, litter_number, gd0_weight, starts_with("pups"))

# Order matters
select(litters_data, litter_number, group, gd0_weight)

select(litters_data, litter_number, group, everything())

select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_born_alive)

# Rename
select(litters_data, GROUP = group, litter_number)
```

## Filtering

```{r}
filter(litters_data, group == "Con7")

filter(litters_data, gd_of_birth == 20)

filter(litters_data, gd_of_birth < 20)

filter(litters_data, gd_of_birth >= 20)

filter(litters_data, pups_born_alive < 6)

filter(litters_data, pups_born_alive < 6, group == "Con7")

# Or
filter(litters_data, group == "Con7" | group == "Mod8")
filter(litters_data, group %in% c("Con7", "Mod8"))

#Selecting from a range
filter(litters_data, pups_born_alive >=4, pups_born_alive <= 6)

#Variable a + b < c 
filter(litters_data, gd0_weight + gd18_weight < 70)

#Missing values
## Don't do this: 
##filter(litters_data, is.na(gd0_weight))
drop_na(litters_data, gd0_weight)

```

